version: '3.4'

services:
  catalog-db:
    image: mongo
  basket-db:
    image: redis
  rabbitmq:
    image: rabbitmq:3-management-alpine
    
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: Basket.API/Dockerfile

